import { Cameras, Promo, ReviewPost, Reviews } from '../types/types';

export const FISH_PROMO : Promo = {
  id: 1,
  name: 'Ретрокамера Dus Auge lV',
  previewImg: 'img/content/promo.jpg',
  previewImg2x: 'img/content/promo@2x.jpg',
  previewImgWebp: 'img/content/promo.webp',
  previewImgWebp2x: 'img/content/promo@2x.webp'
};

export const FISH_PRODUCTS : Cameras = [
  {
    id: 1,
    name: 'Ретрокамера Dus Auge lV',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 2,
    price: 1,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 16,
  },
  {
    id: 2,
    name: 'Ретрокамера',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 3,
    price: 2,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 10,
  },
  {
    id: 3,
    name: 'Ретрокамера Dus Auge lV',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 2,
    price: 3,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 16,
  },
  {
    id: 4,
    name: 'Ретрокамера',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 3,
    price: 4,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 10,
  },
  {
    id: 5,
    name: 'Ретрокамера Dus Auge lV',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 2,
    price: 5,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 16,
  },
  {
    id: 6,
    name: 'Ретрокамера',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 3,
    price: 6,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 10,
  },
  {
    id: 7,
    name: 'Ретрокамера Dus Auge lV',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 2,
    price: 7,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 16,
  },
  {
    id: 8,
    name: 'Ретрокамера',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 3,
    price: 8,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 10,
  },
  {
    id: 9,
    name: 'Ретрокамера',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 3,
    price: 9,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 10,
  },
  {
    id: 10,
    name: 'Ретрокамера',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники.',
    level: 'Любительский',
    rating: 3,
    price: 10,
    previewImg: 'img/content/das-auge.jpg',
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 10,
  },
];

export const FISH_REVIEWS : Reviews = [
  {
    id: 'asf23f23f2-f23f2f2f-f2f32f1f21asdasd2f-2f1f',
    cameraId: 1,
    userName: 'Окунь',
    advantage: 'Мокро',
    disadvantage: 'Сухо',
    rating: 1,
    review: 'Ужасно, воды меньше, чем в дипломе',
    createAt: '2022-10-25T04:38:05.054Z',
  },
  {
    id: 'asf23f23f2-f23f2f2f-f2f32f1fasdfsdf21f1212f-2f1f',
    cameraId: 1,
    userName: 'Окунь',
    advantage: 'Мокро',
    disadvantage: 'Сухо',
    rating: 1,
    review: 'Ужасно, воды меньше, чем в дипломе',
    createAt: '2022-10-25T04:38:05.054Z',
  },
  {
    id: 'asf23f23f2-f23f2f2f-f2f32f1f21dfgdfgf1212f-2f1f',
    cameraId: 1,
    userName: 'Окунь',
    advantage: 'Мокро',
    disadvantage: 'Сухо',
    rating: 1,
    review: 'Ужасно, воды меньше, чем в дипломе',
    createAt: '2022-10-25T04:38:05.054Z',
  },
  {
    id: 'asf23f23f2-f23f2f2f-f2f32f1f21f1221342312f-2f1f',
    cameraId: 1,
    userName: 'Окунь',
    advantage: 'Мокро',
    disadvantage: 'Сухо',
    rating: 1,
    review: 'Ужасно, воды меньше, чем в дипломе',
    createAt: '2022-10-25T04:38:05.054Z',
  },
  {
    id: 'asf23f23f2-f23f2f2f-f2f32dfbdbf1f21f1212f-2f1f',
    cameraId: 1,
    userName: 'Окунь',
    advantage: 'Мокро',
    disadvantage: 'Сухо',
    rating: 1,
    review: 'Ужасно, воды меньше, чем в дипломе',
    createAt: '2022-10-25T04:38:05.054Z',
  },
  {
    id: 'asf23f23f2-f23f2f2f-f2f32f1f21sdfsdfsdf1212f-2f1f',
    cameraId: 1,
    userName: 'Окунь',
    advantage: 'Мокро',
    disadvantage: 'Сухо',
    rating: 1,
    review: 'Ужасно, воды меньше, чем в дипломе',
    createAt: '2022-10-25T04:38:05.054Z',
  },
  {
    id: 'asf23f23f2-f23f2f2f-f2f32f1f21231231f1212f-2f1f',
    cameraId: 1,
    userName: 'Окунь',
    advantage: 'Мокро',
    disadvantage: 'Сухо',
    rating: 1,
    review: 'Ужасно, воды меньше, чем в дипломе',
    createAt: '2022-10-25T04:38:05.054Z',
  },
  {
    id: 'asf23f23f2-f23f2f2f-f2f32f1f21asdascxf1212f-2f1f',
    cameraId: 1,
    userName: 'Окунь',
    advantage: 'Мокро',
    disadvantage: 'Сухо',
    rating: 1,
    review: 'Ужасно, воды меньше, чем в дипломе',
    createAt: '2022-10-25T04:38:05.054Z',
  },
];

export const FISH_REVIEW_POST : ReviewPost = {
  cameraId: 1,
  userName: 'Окунь',
  advantage: 'Мокро',
  disadvantage: 'Сухо',
  rating: 1,
  review: 'Ужасно, воды меньше, чем в дипломе',
};
